// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_first_probe_EV_charger

#ifndef UI_SCREENAJUSTES_H
#define UI_SCREENAJUSTES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAjustes
extern void ui_ScreenAjustes_screen_init(void);
extern void ui_ScreenAjustes_screen_destroy(void);
extern lv_obj_t * ui_ScreenAjustes;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

