// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_first_probe_EV_charger

#include "ui.h"

lv_obj_t * ui_ScreenCarga = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_ScreenCarga_screen_init(void)
{
    ui_ScreenCarga = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCarga, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_ScreenCarga);
    lv_obj_set_width(ui_Button4, 337);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 35);
    lv_obj_set_y(ui_Button4, -25);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Este es el menu de carga,\nregresar a menu principal");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_ScreenCarga_screen_destroy(void)
{
    if(ui_ScreenCarga) lv_obj_del(ui_ScreenCarga);

    // NULL screen variables
    ui_ScreenCarga = NULL;
    ui_Button4 = NULL;
    ui_Label4 = NULL;

}
