// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP32_first_probe_EV_charger

#include "ui.h"

lv_obj_t * ui_ScreenAjustes = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_ScreenAjustes_screen_init(void)
{
    ui_ScreenAjustes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAjustes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_ScreenAjustes);
    lv_obj_set_width(ui_Button3, 281);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 29);
    lv_obj_set_y(ui_Button3, -25);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Este es el menu de ajustes,\nregresar a menu principal");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_ScreenAjustes_screen_destroy(void)
{
    if(ui_ScreenAjustes) lv_obj_del(ui_ScreenAjustes);

    // NULL screen variables
    ui_ScreenAjustes = NULL;
    ui_Button3 = NULL;
    ui_Label3 = NULL;

}
